### ISSUE TITLE
system0 = raw_input((">>>")

### ISSUE THREAD

**Issue by Hasji** [LionSec/xerosploit#306]
Traceback (most recent call last):
  File "/root/xerosploit/./install.py", line 65, in <module>
    main()
  File "/root/xerosploit/./install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined

**Comment by jaynagrecha** [comment]
Your Welcome!

**Comment by XM1N21KR1** [comment]
> Please replace all the "raw_input" with only "input". This will resolve the issue. The updated python uses this new syntax and the keyword "raw_input" has been replaced by "input".

Thankyou!

**Comment by yoitsankey** [comment]
Step1 . Open install.py and xerosploit.py respectively in a text editor.
Step 2. Then Go to Find and Replace.
Step 3. Now, Enter "raw_input" in Find section of find and replace tool (without quotations ).
Step 4. and then Enter "input" in Replace section of find and replace tool (without quotations).
Step 5. Now replace all the occurences with above value.
Step 6. save the file and exit.
Step 7. Now run the install.py with python3 install it.
Step 8. after installation run xerosploit.py with python3 in order to get it working.
Step 9. (optional)
If you want to directly run xerosploit from the terminal instead of using python3 everytime with xerosploit.py, Go to /opt/xersploit, and now find and replace all the occurences of raw_input with input as explained above.

BOOM!!! Congratulations You get it working
